USE siteCercolaFioravante;

ALTER TABLE customer ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE day ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE service ADD COLUMN version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE reservation ADD COLUMN version BIGINT NOT NULL DEFAULT 0;